name: Release Packages

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 1000000
      - name: Lint packages
        run: yarn lint-packages
      - name: Test packages
        run: yarn test-packages

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@blb-ventures'
      - name: Build packages
        run: yarn build-packages
      - name: Publish Packages
        run: yarn publish-packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}